name: Demo two runner

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
       - name: Print runner os
         run: |
            echo "Print running os ${{ runner.os }}"
